name: ad_screening
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - black
  - pre-commit
  - pandas
  - numpy
  - pytorch
  - openpyxl
  - matplotlib
  - seaborn
  - pyyaml
  - scikit-learn
  - attrs
  - rdkit
