name: ad_screening
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - black
  - pre-commit
  - pandas
  - numpy
  - openpyxl
  - matplotlib
  - seaborn
  - pyyaml
  - pip:
      - asyncpg
      - prefect
